name: CPlugin.Net

on: 
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet-version: ['8.x']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Test 
      run: |
        dotnet test ./tests/CPlugin.Net/CPlugin.Net.Tests.csproj -c Release
        dotnet publish ./tests/CPlugin.Net/CPlugin.Net.Tests.csproj -c Release --no-build -o out
        dotnet vstest ./out/CPlugin.Net.Tests.dll
        dotnet build ./samples/Plugins/AppointmentPlugin/Example.AppointmentPlugin.csproj -c Release
        dotnet build ./samples/Plugins/PersonPlugin/Example.PersonPlugin.csproj -c Release
        dotnet build ./samples/Plugins/JsonPlugin/Example.JsonPlugin.csproj -c Release
        dotnet build ./samples/Plugins/OldJsonPlugin/Example.OldJsonPlugin.csproj -c Release
        dotnet build ./samples/Plugins/DependencyInjectionPlugin/Example.DependencyInjectionPlugin.csproj -c Release
        dotnet test ./samples/Test/Example.Test.csproj -c Release